export const vehicles = [
  {
    id: "hsv-gts-2016",
    year: 2016,
    make: "HSV",
    model: "GTS",
    variant: "Gen-F2 · Supercharged sedan",
    price: 94990,
    kms: 58420,
    transmission: "Automatic",
    engine: "6.2L supercharged V8",
    fuel: "Petrol",
    body: "Sedan",
    colour: "Phantom Black",
    power: "430 kW",
    status: "available",
    image: "/images/car-1.jpg",
    tag: "THE ICON",
    stock: "MM101",
    description:
      "An Australian performance icon with unmistakable presence. The Gen-F2 GTS pairs supercharged V8 character with a beautifully appointed cabin. A car for the enthusiast who wants every drive to feel like an occasion.",
  },
  {
    id: "holden-ss-v-redline-2017",
    year: 2017,
    make: "Holden",
    model: "Commodore SS V Redline",
    variant: "VF Series II · V8 sedan",
    price: 64990,
    kms: 72850,
    transmission: "Automatic",
    engine: "6.2L V8",
    fuel: "Petrol",
    body: "Sedan",
    colour: "Heron White",
    power: "304 kW",
    status: "available",
    image: "/images/car-2.jpg",
    tag: "JUST ARRIVED",
    stock: "MM102",
    description:
      "A fitting celebration of the Australian-built Commodore. The SS V Redline brings together the character of a naturally aspirated V8, everyday comfort and a purposeful stance.",
  },
  {
    id: "hsv-clubsport-r8-2015",
    year: 2015,
    make: "HSV",
    model: "Clubsport R8",
    variant: "Gen-F · V8 sedan",
    price: 59990,
    kms: 89300,
    transmission: "Manual",
    engine: "6.2L V8",
    fuel: "Petrol",
    body: "Sedan",
    colour: "Sting Red",
    power: "340 kW",
    status: "available",
    image: "/images/car-3.jpg",
    tag: "ENTHUSIAST PICK",
    stock: "MM103",
    description:
      "Big V8 character, a manual gearbox and the unmistakable HSV attitude. The Clubsport R8 is made for people who appreciate the connection between car and driver.",
  },
  {
    id: "holden-redline-ute-2017",
    year: 2017,
    make: "Holden",
    model: "SS V Redline Ute",
    variant: "VF Series II · V8 ute",
    price: 69990,
    kms: 62300,
    transmission: "Manual",
    engine: "6.2L V8",
    fuel: "Petrol",
    body: "Ute",
    colour: "Nitrate Silver",
    power: "304 kW",
    status: "available",
    image: "/images/car-4.jpg",
    tag: "",
    stock: "MM104",
    description:
      "An iconic Australian combination of practicality and performance. The final-generation Redline ute delivers V8 character with a purposeful cabin and a silhouette that needs no introduction.",
  },
  {
    id: "ford-mustang-gt-2019",
    year: 2019,
    make: "Ford",
    model: "Mustang GT",
    variant: "Fastback · V8 coupe",
    price: 57990,
    kms: 41600,
    transmission: "Automatic",
    engine: "5.0L V8",
    fuel: "Petrol",
    body: "Coupe",
    colour: "Magnetic Grey",
    power: "339 kW",
    status: "available",
    image: "/images/car-5.jpg",
    tag: "",
    stock: "MM105",
    description:
      "A modern muscle car with a timeless shape. The Mustang GT delivers an unmistakable V8 soundtrack and an engaging drive, wrapped in classic fastback styling.",
  },
  {
    id: "hsv-maloo-r8-2014",
    year: 2014,
    make: "HSV",
    model: "Maloo R8",
    variant: "Gen-F · V8 ute",
    price: 67990,
    kms: 76400,
    transmission: "Automatic",
    engine: "6.2L V8",
    fuel: "Petrol",
    body: "Ute",
    colour: "Phantom Black",
    power: "340 kW",
    status: "available",
    image: "/images/car-6.jpg",
    tag: "",
    stock: "MM106",
    description:
      "Distinctive, purposeful and uniquely Australian. The Maloo R8 takes HSV performance and gives it a shape all its own.",
  },
  {
    id: "hsv-clubsport-2012",
    year: 2012,
    make: "HSV",
    model: "Clubsport",
    variant: "E Series 3 · V8 sedan",
    price: 42990,
    kms: 106200,
    transmission: "Automatic",
    engine: "6.2L V8",
    fuel: "Petrol",
    body: "Sedan",
    colour: "Heron White",
    power: "317 kW",
    status: "sold",
    image: "/images/car-7.jpg",
    tag: "FOUND ITS NEXT DRIVER",
    stock: "MM097",
    description:
      "This Clubsport has found its next enthusiast. Looking for something similar? Get in touch with Madi to discuss what you have in mind.",
  },
  {
    id: "holden-ss-2016",
    year: 2016,
    make: "Holden",
    model: "Commodore SS",
    variant: "VF Series II · V8 sedan",
    price: 46990,
    kms: 98100,
    transmission: "Manual",
    engine: "6.2L V8",
    fuel: "Petrol",
    body: "Sedan",
    colour: "Sting Red",
    power: "304 kW",
    status: "sold",
    image: "/images/car-8.jpg",
    tag: "FOUND ITS NEXT DRIVER",
    stock: "MM098",
    description:
      "This V8 Commodore has found a new home. Talk to us about another Australian performance car from our collection.",
  },
];
export const money = (n) =>
  new Intl.NumberFormat("en-AU", {
    style: "currency",
    currency: "AUD",
    maximumFractionDigits: 0,
  }).format(n);
export const number = (n) => new Intl.NumberFormat("en-AU").format(n);
export const business = {
  phone: "0411 710 409",
  tel: "+61411710409",
  address: "Unit 4/405A Grand Junction Road",
  suburb: "Wingfield SA 5013",
  maps: "https://www.google.com/maps/search/?api=1&query=MM+Prestige+Motors+Unit+4+405A+Grand+Junction+Road+Wingfield+SA+5013",
};
